Que2.-
In this dataset you have to predict that whether we have to give ATTORNEY to the clients or not (0=Yes, 1=No) based on below factors.
CLMAGE - Age of Client
CLMSEX - Sex of client (0=Male, 1= Female)
SEATBELT - Whether client has Seatbelt or not (0=Yes, 1=No)
CLMINSUR - Whether Client give Insurance or not (0=Yes, 1=No)
LOSS - Loss that client faced

Prepare model by using logistic regression,Naive Bayes,KNN and SVM & Also calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score, roc auc score, precision, recall.

Dataset : Claimants.csv

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
df = pd.read_csv('Claimants.csv')
df.head(3)

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0         0     0.0       1.0       0.0    50.0  34.940
1         1     1.0       0.0       0.0    18.0   0.891
2         1     0.0       1.0       0.0     5.0   0.330

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   ATTORNEY  1340 non-null   int64  
 1   CLMSEX    1328 non-null   float64
 2   CLMINSUR  1299 non-null   float64
 3   SEATBELT  1292 non-null   float64
 4   CLMAGE    1151 non-null   float64
 5   LOSS      1340 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 62.9 KB


In [33]:
df.describe()

ATTORNEY       CLMSEX     CLMINSUR     SEATBELT       CLMAGE  \
count  1340.000000  1328.000000  1299.000000  1292.000000  1151.000000   
mean      0.488806     0.558735     0.907621     0.017028    28.414422   
std       0.500061     0.496725     0.289671     0.129425    20.304451   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     1.000000     0.000000     9.000000   
50%       0.000000     1.000000     1.000000     0.000000    30.000000   
75%       1.000000     1.000000     1.000000     0.000000    43.000000   
max       1.000000     1.000000     1.000000     1.000000    95.000000   

              LOSS  
count  1340.000000  
mean      3.806307  
std      10.636903  
min       0.000000  
25%       0.400000  
50%       1.069500  
75%       3.781500  
max     173.604000

In [15]:
df.corr()

ATTORNEY    CLMSEX  CLMINSUR  SEATBELT    CLMAGE      LOSS
ATTORNEY  1.000000  0.079674  0.079439 -0.057189  0.010680 -0.219715
CLMSEX    0.079674  1.000000  0.066413 -0.015024 -0.023195 -0.027611
CLMINSUR  0.079439  0.066413  1.000000  0.021154  0.049493  0.005821
SEATBELT -0.057189 -0.015024  0.021154  1.000000 -0.027992  0.111189
CLMAGE    0.010680 -0.023195  0.049493 -0.027992  1.000000  0.064612
LOSS     -0.219715 -0.027611  0.005821  0.111189  0.064612  1.000000

In [34]:
df.drop(['CLMSEX','CLMINSUR','SEATBELT','CLMAGE'], axis=1,inplace=True)
X = df.drop(['ATTORNEY'],axis=1)
y = df['ATTORNEY']

In [35]:
from sklearn.model_selection import train_test_split


x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=12345)

In [36]:
def build_logistic_regression():
    from sklearn.linear_model import LogisticRegressionCV
    
    # create a model
    model = LogisticRegressionCV()

    # train the model
    model.fit(x_train, y_train)

    return model

In [37]:
def build_naive_bayes_model():
    from sklearn.naive_bayes import GaussianNB
    
    # create a model
    model = GaussianNB()

    # train the model
    model.fit(x_train, y_train)

    return model

In [38]:
def build_knn_model():
    from sklearn.neighbors import KNeighborsClassifier

    # create a model
    model = KNeighborsClassifier(n_neighbors=9)

    # train the model
    model.fit(x_train, y_train)

    return model

In [39]:
def build_svm_model():
    from sklearn.svm import SVC

    # create a model
    model = SVC()

    # train the model
    model.fit(x_train, y_train)

    return model

In [40]:
# get Logistic Regression model
model_lg = build_logistic_regression()

# get nb model
model_nb = build_naive_bayes_model()

# get KNN model
model_knn = build_knn_model()

# get SVM model
model_svm = build_svm_model()

In [41]:
def evaluate_model(model):
    from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

    # define y_true and y_pred
    y_true = y_test
    y_pred = model.predict(x_test)    

    # get confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    print(cm)

    # print accuracy
    print(f"accuracy = {accuracy_score(y_true, y_pred) * 100:.2f}")
    print(f"precision = {precision_score(y_true, y_pred) * 100:.2f}")
    print(f"recall = {recall_score(y_true, y_pred) * 100:.2f}")
    print(f"F1 score = {f1_score(y_true, y_pred) * 100:.2f}")

In [44]:
evaluate_model(model_lg)

[[114  95]
 [ 34 160]]
accuracy = 67.99
precision = 62.75
recall = 82.47
F1 score = 71.27


In [45]:
evaluate_model(model_nb)

[[ 50 159]
 [  8 186]]
accuracy = 58.56
precision = 53.91
recall = 95.88
F1 score = 69.02


In [46]:
evaluate_model(model_knn)

[[138  71]
 [ 56 138]]
accuracy = 68.49
precision = 66.03
recall = 71.13
F1 score = 68.49


In [47]:
evaluate_model(model_svm)

[[117  92]
 [ 38 156]]
accuracy = 67.74
precision = 62.90
recall = 80.41
F1 score = 70.59
